// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: combination.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Combination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PIDs    []uint32  `protobuf:"varint,1,rep,packed,name=PIDs,proto3" json:"PIDs,omitempty"`
	Packets []*Packet `protobuf:"bytes,2,rep,name=Packets,proto3" json:"Packets,omitempty"`
}

func (x *Combination) Reset() {
	*x = Combination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combination_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Combination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Combination) ProtoMessage() {}

func (x *Combination) ProtoReflect() protoreflect.Message {
	mi := &file_combination_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Combination.ProtoReflect.Descriptor instead.
func (*Combination) Descriptor() ([]byte, []int) {
	return file_combination_proto_rawDescGZIP(), []int{0}
}

func (x *Combination) GetPIDs() []uint32 {
	if x != nil {
		return x.PIDs
	}
	return nil
}

func (x *Combination) GetPackets() []*Packet {
	if x != nil {
		return x.Packets
	}
	return nil
}

type ServerCombination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID    string       `protobuf:"bytes,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	Combination *Combination `protobuf:"bytes,2,opt,name=Combination,proto3" json:"Combination,omitempty"`
}

func (x *ServerCombination) Reset() {
	*x = ServerCombination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combination_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerCombination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCombination) ProtoMessage() {}

func (x *ServerCombination) ProtoReflect() protoreflect.Message {
	mi := &file_combination_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCombination.ProtoReflect.Descriptor instead.
func (*ServerCombination) Descriptor() ([]byte, []int) {
	return file_combination_proto_rawDescGZIP(), []int{1}
}

func (x *ServerCombination) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

func (x *ServerCombination) GetCombination() *Combination {
	if x != nil {
		return x.Combination
	}
	return nil
}

type Combinations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Combinations []*Combination `protobuf:"bytes,1,rep,name=Combinations,proto3" json:"Combinations,omitempty"`
}

func (x *Combinations) Reset() {
	*x = Combinations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combination_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Combinations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Combinations) ProtoMessage() {}

func (x *Combinations) ProtoReflect() protoreflect.Message {
	mi := &file_combination_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Combinations.ProtoReflect.Descriptor instead.
func (*Combinations) Descriptor() ([]byte, []int) {
	return file_combination_proto_rawDescGZIP(), []int{2}
}

func (x *Combinations) GetCombinations() []*Combination {
	if x != nil {
		return x.Combinations
	}
	return nil
}

var File_combination_proto protoreflect.FileDescriptor

var file_combination_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x04, 0x50, 0x49, 0x44, 0x73, 0x12, 0x24, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x62,
	0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x31, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x43, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x33, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f,
	0x6d, 0x62, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x43, 0x6f, 0x6d, 0x62, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_combination_proto_rawDescOnce sync.Once
	file_combination_proto_rawDescData = file_combination_proto_rawDesc
)

func file_combination_proto_rawDescGZIP() []byte {
	file_combination_proto_rawDescOnce.Do(func() {
		file_combination_proto_rawDescData = protoimpl.X.CompressGZIP(file_combination_proto_rawDescData)
	})
	return file_combination_proto_rawDescData
}

var file_combination_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_combination_proto_goTypes = []interface{}{
	(*Combination)(nil),       // 0: pb.Combination
	(*ServerCombination)(nil), // 1: pb.ServerCombination
	(*Combinations)(nil),      // 2: pb.Combinations
	(*Packet)(nil),            // 3: pb.Packet
}
var file_combination_proto_depIdxs = []int32{
	3, // 0: pb.Combination.Packets:type_name -> pb.Packet
	0, // 1: pb.ServerCombination.Combination:type_name -> pb.Combination
	0, // 2: pb.Combinations.Combinations:type_name -> pb.Combination
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_combination_proto_init() }
func file_combination_proto_init() {
	if File_combination_proto != nil {
		return
	}
	file_packet_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_combination_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Combination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combination_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerCombination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combination_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Combinations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_combination_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_combination_proto_goTypes,
		DependencyIndexes: file_combination_proto_depIdxs,
		MessageInfos:      file_combination_proto_msgTypes,
	}.Build()
	File_combination_proto = out.File
	file_combination_proto_rawDesc = nil
	file_combination_proto_goTypes = nil
	file_combination_proto_depIdxs = nil
}
