// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: enter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID  uint32  `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Name string  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	X    float32 `protobuf:"fixed32,3,opt,name=X,proto3" json:"X,omitempty"`
	Z    float32 `protobuf:"fixed32,4,opt,name=Z,proto3" json:"Z,omitempty"`
}

func (x *Enter) Reset() {
	*x = Enter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enter) ProtoMessage() {}

func (x *Enter) ProtoReflect() protoreflect.Message {
	mi := &file_enter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enter.ProtoReflect.Descriptor instead.
func (*Enter) Descriptor() ([]byte, []int) {
	return file_enter_proto_rawDescGZIP(), []int{0}
}

func (x *Enter) GetPID() uint32 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *Enter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enter) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Enter) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_enter_proto protoreflect.FileDescriptor

var file_enter_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x49, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x50, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x58, 0x12, 0x0c,
	0x0a, 0x01, 0x5a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x5a, 0x42, 0x06, 0x5a, 0x04,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enter_proto_rawDescOnce sync.Once
	file_enter_proto_rawDescData = file_enter_proto_rawDesc
)

func file_enter_proto_rawDescGZIP() []byte {
	file_enter_proto_rawDescOnce.Do(func() {
		file_enter_proto_rawDescData = protoimpl.X.CompressGZIP(file_enter_proto_rawDescData)
	})
	return file_enter_proto_rawDescData
}

var file_enter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_enter_proto_goTypes = []interface{}{
	(*Enter)(nil), // 0: pb.Enter
}
var file_enter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enter_proto_init() }
func file_enter_proto_init() {
	if File_enter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enter_proto_goTypes,
		DependencyIndexes: file_enter_proto_depIdxs,
		MessageInfos:      file_enter_proto_msgTypes,
	}.Build()
	File_enter_proto = out.File
	file_enter_proto_rawDesc = nil
	file_enter_proto_goTypes = nil
	file_enter_proto_depIdxs = nil
}
