// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: on_out_of_view.proto

package push

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnOutOfView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID uint32 `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
}

func (x *OnOutOfView) Reset() {
	*x = OnOutOfView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_on_out_of_view_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnOutOfView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOutOfView) ProtoMessage() {}

func (x *OnOutOfView) ProtoReflect() protoreflect.Message {
	mi := &file_on_out_of_view_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOutOfView.ProtoReflect.Descriptor instead.
func (*OnOutOfView) Descriptor() ([]byte, []int) {
	return file_on_out_of_view_proto_rawDescGZIP(), []int{0}
}

func (x *OnOutOfView) GetPID() uint32 {
	if x != nil {
		return x.PID
	}
	return 0
}

var File_on_out_of_view_proto protoreflect.FileDescriptor

var file_on_out_of_view_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6f, 0x6e, 0x5f, 0x6f, 0x75, 0x74, 0x5f, 0x6f, 0x66, 0x5f, 0x76, 0x69, 0x65, 0x77,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x75, 0x73, 0x68, 0x22, 0x1f, 0x0a, 0x0b,
	0x4f, 0x6e, 0x4f, 0x75, 0x74, 0x4f, 0x66, 0x56, 0x69, 0x65, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x50,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x50, 0x49, 0x44, 0x42, 0x08, 0x5a,
	0x06, 0x2f, 0x3b, 0x70, 0x75, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_on_out_of_view_proto_rawDescOnce sync.Once
	file_on_out_of_view_proto_rawDescData = file_on_out_of_view_proto_rawDesc
)

func file_on_out_of_view_proto_rawDescGZIP() []byte {
	file_on_out_of_view_proto_rawDescOnce.Do(func() {
		file_on_out_of_view_proto_rawDescData = protoimpl.X.CompressGZIP(file_on_out_of_view_proto_rawDescData)
	})
	return file_on_out_of_view_proto_rawDescData
}

var file_on_out_of_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_on_out_of_view_proto_goTypes = []interface{}{
	(*OnOutOfView)(nil), // 0: push.OnOutOfView
}
var file_on_out_of_view_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_on_out_of_view_proto_init() }
func file_on_out_of_view_proto_init() {
	if File_on_out_of_view_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_on_out_of_view_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnOutOfView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_on_out_of_view_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_on_out_of_view_proto_goTypes,
		DependencyIndexes: file_on_out_of_view_proto_depIdxs,
		MessageInfos:      file_on_out_of_view_proto_msgTypes,
	}.Build()
	File_on_out_of_view_proto = out.File
	file_on_out_of_view_proto_rawDesc = nil
	file_on_out_of_view_proto_goTypes = nil
	file_on_out_of_view_proto_depIdxs = nil
}
